"""
Module 3.5 — Optimization Engine orchestrator.

Routes between two solve strategies by problem shape (spec-review issue #6):
- ENUMERATION when at least one candidate can cover the full cargo alone
  (the common case) — closed-form argmin over the risk-adjusted objective,
  no solver needed.
- MIP (OR-Tools MPSolver/CBC) only when NO single candidate suffices and
  cargo must be split across multiple vessels.

This is the module that finally calls 3.6 (risk) per candidate and combines
expected_cost + risk_lambda*(cvar-expected_cost) to rank/select — matching
the Section 8 orchestration sequence: 3.1 -> 3.2 -> 3.3 -> 3.4 -> [3.5 <-> 3.6] -> DecisionResult.
"""
from __future__ import annotations

from app import config
from app.optimization.enumerate import enumerate_single_vessel_candidates
from app.optimization.mip_model import solve_split_cargo
from app.risk.metrics import compute_combined_risk, risk_adjusted_objective
from app.risk.preference_mapping import get_risk_lambda
from app.schemas.candidates import CandidateSet, CostMatrix
from app.schemas.common import CargoRequirement, PortFeasibilityResult, RouteDistance, ScenarioSet, Vessel
from app.schemas.optimization_result import OptimizationResult, RankedAlternative, RejectedSummaryItem, SelectedLeg


def run_optimization(
    optimization_run_id: str,
    cargo: CargoRequirement,
    candidate_set: CandidateSet,
    cost_matrix: CostMatrix,
    scenario_set: ScenarioSet,
    port_feasibility: PortFeasibilityResult,
    distances: list[RouteDistance],
    vessels: list[Vessel],
) -> OptimizationResult:
    """Module 3.5 entry point."""
    risk_lambda = get_risk_lambda(cargo.risk_preference)

    if candidate_set.status != "OK":
        return OptimizationResult(
            optimization_run_id=optimization_run_id,
            cargo_requirement_id=cargo.cargo_requirement_id,
            solve_method="NONE",
            status="NO_FEASIBLE_STRATEGY",
            risk_aversion_lambda=risk_lambda,
            rejected_summary=[RejectedSummaryItem(reason=n) for n in candidate_set.generation_notes],
            notes=["No candidates were generated by 3.3 — see rejected_summary for upstream reasons."],
        )

    non_null = candidate_set.non_null_candidates
    full_capacity_candidates = [c for c in non_null if c.capacity_tonnes >= cargo.quantity_tonnes]
    split_eligible_candidates = [c for c in non_null if c.split_eligible]

    if full_capacity_candidates:
        return _solve_via_enumeration(
            optimization_run_id, cargo, full_capacity_candidates, cost_matrix, scenario_set, risk_lambda, vessels
        )

    if split_eligible_candidates:
        return _solve_via_mip(
            optimization_run_id, cargo, split_eligible_candidates, cost_matrix, scenario_set,
            port_feasibility, distances, vessels, risk_lambda,
        )

    return OptimizationResult(
        optimization_run_id=optimization_run_id,
        cargo_requirement_id=cargo.cargo_requirement_id,
        solve_method="NONE",
        status="NO_FEASIBLE_STRATEGY",
        risk_aversion_lambda=risk_lambda,
        notes=["Candidates exist but none can cover the cargo alone or via a split — NO_FEASIBLE_STRATEGY."],
    )


def _solve_via_enumeration(optimization_run_id, cargo, full_capacity_candidates, cost_matrix, scenario_set, risk_lambda, vessels) -> OptimizationResult:
    scores = enumerate_single_vessel_candidates(full_capacity_candidates, cargo, cost_matrix, scenario_set, risk_lambda, vessels=vessels)
    winner = scores[0]
    alternatives = [
        RankedAlternative(candidate_id=s.candidate.candidate_id, expected_cost=s.expected_cost, cvar=s.cvar, rank=i + 1)
        for i, s in enumerate(scores[: config.RANKED_ALTERNATIVES_TOP_N])
    ]
    return OptimizationResult(
        optimization_run_id=optimization_run_id,
        cargo_requirement_id=cargo.cargo_requirement_id,
        solve_method="ENUMERATION",
        status="OPTIMAL",
        selected=[SelectedLeg(candidate_id=winner.candidate.candidate_id, tonnage=cargo.quantity_tonnes)],
        expected_cost=winner.expected_cost,
        cvar_80=winner.cvar,
        cvar_status=winner.cvar_status,
        objective_value=winner.objective_value,
        risk_aversion_lambda=risk_lambda,
        vessel_reliability_score=winner.reliability_score,
        reliability_flag=winner.reliability_flag,
        ranked_alternatives=alternatives,
    )


def _solve_via_mip(optimization_run_id, cargo, split_eligible_candidates, cost_matrix, scenario_set, port_feasibility, distances, vessels, risk_lambda) -> OptimizationResult:
    mip_result = solve_split_cargo(cargo, split_eligible_candidates, cost_matrix, scenario_set, vessels, port_feasibility, distances)

    if mip_result.status == "INFEASIBLE":
        return OptimizationResult(
            optimization_run_id=optimization_run_id,
            cargo_requirement_id=cargo.cargo_requirement_id,
            solve_method="MIP",
            status="NO_FEASIBLE_STRATEGY",
            risk_aversion_lambda=risk_lambda,
            notes=[mip_result.infeasibility_reason or "Split-cargo MIP found no feasible combination (no further diagnostic available)."],
        )

    # reliability_scores must be keyed by CANDIDATE_id (each split leg is a
    # candidate, not directly a vessel) — build that via each candidate's vessel_id.
    vessel_by_id = {v.vessel_id: v for v in vessels}
    candidate_by_id = {c.candidate_id: c for c in split_eligible_candidates}
    reliability_by_candidate = {}
    for candidate_id, _ in mip_result.selected:
        candidate = candidate_by_id.get(candidate_id)
        vessel = vessel_by_id.get(candidate.vessel_id) if candidate else None
        reliability_by_candidate[candidate_id] = vessel.reliability_score if vessel else None

    combined_risk = compute_combined_risk(
        "SPLIT_COMBO", mip_result.selected, cost_matrix, scenario_set,
        reliability_scores=reliability_by_candidate,
    )
    # Reported for transparency (post-hoc, per mip_model.py's stated simplification) —
    # NOT what the MIP search itself optimized on.
    reported_objective = risk_adjusted_objective(combined_risk.expected_cost, combined_risk.cvar, risk_lambda)

    return OptimizationResult(
        optimization_run_id=optimization_run_id,
        cargo_requirement_id=cargo.cargo_requirement_id,
        solve_method="MIP",
        status=mip_result.status,  # "OPTIMAL" or "TIME_LIMIT_REACHED"
        selected=[SelectedLeg(candidate_id=cid, tonnage=t) for cid, t in mip_result.selected],
        expected_cost=combined_risk.expected_cost,
        cvar_80=combined_risk.cvar,
        cvar_status=combined_risk.cvar_status,
        objective_value=reported_objective,
        risk_aversion_lambda=risk_lambda,
        vessel_reliability_score=combined_risk.vessel_reliability_score,
        reliability_flag=combined_risk.reliability_flag,
        notes=[
            "Split-cargo MIP objective minimized EXPECTED COST ONLY (stated simplification — "
            "see mip_model.py). The expected_cost/cvar_80/objective_value fields above are the "
            "REALIZED risk of the search's chosen combination, computed post-hoc for transparency, "
            "not used to steer the search itself."
        ],
    )
